// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  apiKey: "AIzaSyCKe_Q_5hepTxX0dzXsE1YjPtn_THwXBTs",
  authDomain: "studio-3195176774-5b58f.firebaseapp.com",
  projectId: "studio-3195176774-5b58f",
  storageBucket: "studio-3195176774-5b58f.appspot.com",
  messagingSenderId: "427639378280",
  appId: "1:427639378280:web:d3d9343aaef32f1b4906dd",
  measurementId: ""
};
